# Exported from Render on 2024-05-14T08:26:19Z
services:
  - type: web
    name: goopi
    runtime: python
    repo: https://github.com/mfshaho/goopi
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: API_KEY
        fromService:
          name: goopi
          type: ""
          property: host
    region: frankfurt
    buildCommand: pip3 install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
version: "1"
